### ISSUE TITLE
Socratic Seminar 120: Topic Suggestions

### ISSUE THREAD

**Issue by btsea** [BitDevsNYC/BitDevsNYC.github.io#117]
If you'd like to suggest a topic for the upcoming meetup, please feel free to drop it here! All contributions welcome.

**Comment by Xekyo** [comment]
Confiscation Txs on BSV with API now: https://twitter.com/rot13maxi/status/1613721169257021442

**Comment by pinheadmz** [comment]
## Lightning-Dev

[Swap-in-Potentiam: Moving Onchain Funds "Instantly" To Lightning](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-January/003810.html)

[Efficient Factories For Lightning Channels](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-January/003827.html)

[A security review of Validating Lightning Signer architecture and code](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-January/003829.html)

## Bitcoin-Dev

[OP_VAULT: a new vault proposal](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-January/021318.html) 

[Serverless Payjoin](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-January/021364.html)

## BLIPs

[Inbound routing fees using `channel_update` by Joost Jager](https://github.com/lightning/blips/pull/18)

[Backwards-compatible inbound fees using `inbound_fees_update` by Matt Corallo](https://github.com/lightning/blips/pull/22)

## InfoSec

[LastPass hacked](https://blog.lastpass.com/2022/12/notice-of-recent-security-incident/)

[LukeDashjr server hacked, postmortem analysis by "lordx64"](https://lordx64.medium.com/multiple-linux-backdoors-discovered-targeting-bitcoin-core-developer-technical-analysis-793f8491f561)

## Miscellaneous

[Layer 2 Labs raises $3M to build drivechains](https://www.coindesk.com/tech/2022/12/20/bitcoin-development-company-layer-2-labs-raises-3m-to-bring-drivechains-to-network/)
