### ISSUE TITLE
Socratic Seminar 129 (October 2023): Topic Suggestions

### ISSUE THREAD

**Issue by btsea** [BitDevsNYC/BitDevsNYC.github.io#144]
If you'd like to suggest a topic for the upcoming meetup, please feel free to drop it here! All contributions welcome.

**Comment by DanGould** [comment]
We should talk about the OP_CAT proposal https://github.com/EthanHeilman/op_cat_draft/blob/main/cat.mediawiki, the few basic capabilities it enables, and how it's already got a semblance of consensus without major pushback or flaws since it's been enabled in the past.
