### ISSUE TITLE
Socratic Seminar 130 (November 30th, 2023): Topic Discussions

### ISSUE THREAD

**Issue by btsea** [BitDevsNYC/BitDevsNYC.github.io#146]
Please post topic suggestions here, thank you so much!

**Comment by ecurrencyhodler** [comment]
6.5MM sat bitvm bounty paid through key send.

https://x.com/stakwork/status/1722325849201053986?s=46

And 83 btc fee potentially as a result of compromised wallet and multiple attackers bidding for 100+ btc. https://x.com/mononautical/status/1728946778798793126?s=46
