### ISSUE TITLE
Socratic Seminar 133 (2024-02-29) Topic Collection 

### ISSUE THREAD

**Issue by btsea** [BitDevsNYC/BitDevsNYC.github.io#153]
Please post links to topics that you would be interested in discussing at our next Socratic Seminar! Thank you for your contributions.

**Comment by eisenbruch** [comment]
This will be my first socratic seminar.
I am not a developer - I am a product designer and manager.

Fees are crazy (again)!
I am interested in hearing about what may be in the works to help with fees, if anything.
Probably a boring subject for many who are not new to these seminars  :)

I am also super excited to attend my first Socratic Seminar to meet amazing people!

**Comment by murchandamus** [comment]
Closing as this event has passed
