### ISSUE TITLE
Whirlpool Stats dead link

### ISSUE THREAD

**Issue by MarcoFalke** [BitDevsNYC/BitDevsNYC.github.io#53]
I am wondering what it is about

https://bitdevs.org/2020-04-30-solo-socratic-1#network-data

https://docs.google.com/spreadsheets/d/e/2PACX-1vSq7Z_5bmXCBljAzGCd89ZZa4yicBPrh7DQ_IF2SZfyCrNaAIMeXeyUv2X5a2m1yQKhWSiA367jQpux/pubhtml?gid=0&single=true

**Comment by jnewbery** [comment]
Unfortunately it's expected that some of the links we publish die. There's not really anything we can do about that. I don't think it's worth our time trying to curate links from old newsletters.

**Comment by MarcoFalke** [comment]
Yeah, makes sense. Thx.
