### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by justinmoon** [BitDevsNYC/BitDevsNYC.github.io#61]
Hey. I'm copying your beautiful site for the Austin meetup. I had [this error](https://stackoverflow.com/questions/63335953/jekyll-error-building-page-related-to-kramdown-parser). After adding `gem "kramdown-parser-gfm"` to the `Gemfile` as suggested, then `bundle exec jekyll serve` worked.

I'm a complete Ruby noob so not going to PR the change because I don't know if it's necessary, but thought I'd leave a note for you guys.

**Comment by btsea** [comment]
Thanks for the note @justinmoon :)
